pipeline:
  orgIdentifier: default
  projectIdentifier: HireBurch
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1709002995006
        repoName: SloshBurch/jhttp
  stages:
    - stage:
        name: build
        identifier: build
        template:
          templateRef: Build_Template
          versionLabel: "1.0"
          templateInputs:
            type: CI
            spec:
              execution:
                steps:
                  - step:
                      identifier: dockerbuild
                      type: Plugin
                      spec:
                        settings:
                          password: <+input>
                          username: <+input>
  identifier: Build_jhttp_Template_Usage
  tags: {}
  name: Build jhttp - Template Usage
